# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuración de las máquinas virtuales
  config.vm.define "master6" do |master|
    master.vm.box = "debian/bullseye64"
    master.vm.network "private_network", ip: "192.168.20.10"
    master.vm.hostname = "master6"

    # Configuración de la instalación y configuración de Bind9
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y bind9 bind9-utils

      cp -v /vagrant/config/master/named /etc/default/
      cp -v /vagrant/config/master/named.* /etc/bind/
      cp -v /vagrant/config/master/db.* /var/lib/bind/    

      sudo systemctl restart bind9
    SHELL
  end

  config.vm.define "slave6" do |slave|
    slave.vm.box = "debian/bullseye64"
    slave.vm.network "private_network", ip: "192.168.20.11"
    slave.vm.hostname = "slave6"

    # Configuración de la instalación y configuración de Bind9
    slave.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y bind9 bind9-utils

      cp -v /vagrant/config/slave/named /etc/default/
      cp -v /vagrant/config/slave/named.* /etc/bind/
      
      sudo systemctl restart bind9
    SHELL
  end
end